# Generated by Django 3.0.1 on 2020-01-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookAddition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('is_agree', models.BooleanField()),
                ('is_new', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cook_addition',
            },
        ),
        migrations.CreateModel(
            name='CookAgreement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cook_id', models.IntegerField()),
                ('is_access_granted', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
            ],
            options={
                'db_table': 'cook_agreements',
            },
        ),
        migrations.CreateModel(
            name='CookLocationMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cook_id', models.IntegerField()),
                ('location_id', models.IntegerField()),
            ],
            options={
                'db_table': 'cook_location_mapping',
            },
        ),
        migrations.CreateModel(
            name='CookProfileImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cook_id', models.IntegerField()),
                ('profile_pic', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'cook_profile_image',
            },
        ),
        migrations.CreateModel(
            name='CookSpecilityMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cook_id', models.IntegerField()),
                ('specility_id', models.IntegerField()),
            ],
            options={
                'db_table': 'cook_specility_mapping',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('area', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Specility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('north_indian_food', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('south_indian_food', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('chinees_food', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('other', models.CharField(blank=True, max_length=500, null=True)),
                ('food_pic_one', models.CharField(blank=True, max_length=200, null=True)),
                ('food_pic_two', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'specility',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Cook', 'Cook'), ('Hire', 'Hire')], max_length=10)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10)),
                ('pan_card', models.CharField(max_length=20)),
                ('profile_pic', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_number_one', models.CharField(max_length=10)),
                ('contact_number_two', models.CharField(blank=True, max_length=10, null=True)),
                ('descriptions', models.TextField(default=None)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
