# Generated by Django 3.0.1 on 2020-01-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userdetails_is_access_granted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='pan_card',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
